# Generated by Django 4.0.4 on 2022-05-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('bat', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cellar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('cellar', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Dune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('dune', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Ecanto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('ecanto', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Koati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('kot', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('mat', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Moonfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('moon', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Morbius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('mob', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OldGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('old', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Riverdance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('river', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Stowaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('stow', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TIB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('tib', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('turn', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Uncharted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('charted', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='movie/%y')),
            ],
        ),
        migrations.CreateModel(
            name='VideoD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('videod', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('vivo', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='X',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('x', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
            ],
        ),
        migrations.CreateModel(
            name='YesDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField(default=True, max_length=1000)),
                ('yesday', models.FileField(upload_to='movie/%y')),
                ('thumb', models.FileField(blank=True, upload_to='thumb/%y')),
            ],
        ),
    ]
